[features]
seeds = true
skip-lint = false

[programs.localnet]
gpl_session = "KeyspM2ssCJbqUhQ4k7sveSiY4WjnYsrXkC8oDbwde5"

[programs.devnet]
gpl_session = "KeyspM2ssCJbqUhQ4k7sveSiY4WjnYsrXkC8oDbwde5"

[programs.mainnet]
gpl_session = "KeyspM2ssCJbqUhQ4k7sveSiY4WjnYsrXkC8oDbwde5"

[[test.genesis]]
address="cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program="test-programs/spl_account_compression.so"

[[test.genesis]]
address="noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program="test-programs/spl_noop.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
